const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('lastset-diagnostics.js','utf8');
const logs=[];
const original={log(...a){logs.push(a)},warn(){},error(){},info(){}};
const context={console:original,Date,Error,Number,String,Object,Array,Math};
context.globalThis=context;context.__LASTSET_TEST_ONLY__=true;
vm.createContext(context);
vm.runInContext(source,context);
const T=context.LastSetDiagnosticsTest;
assert(T,'Diagnostics test hooks not available');
assert.equal(T.redact('bearer abc.DEF= x@y.com').includes('abc.DEF'),false);
assert(T.redact('bearer abc.DEF= x@y.com').includes('[EMAIL]'));
assert(!T.redact('api_key=abcd1234 password:secret123').includes('abcd1234'));
assert(!T.redact('api_key=abcd1234 password:secret123').includes('secret123'));
assert.equal(T.withinHotspot(380,20,390),true);
assert.equal(T.withinHotspot(120,30,390),false);
assert.equal(T.tap(380,20,390,1000),false);
assert.equal(T.tap(380,20,390,1250),false);
assert.equal(T.tap(380,20,390,1500),true);
assert.equal(T.tap(380,20,390,2500),false);
assert.equal(T.tap(120,20,390,2700),false);
assert.equal(T.tap(380,20,390,2800),false);
assert.equal(T.tap(380,20,390,3100),false);
assert.equal(T.tap(380,20,390,3300),true);
assert.equal(T.printable({workouts:['private']}),'[Object]');
assert.equal(T.printable(['private']),'[Array]');
original.error('credentials?');
context.console.log('Console is captured');
assert(context.LastSetDiagnostics.logs().some(s=>s.includes('Console is captured')));
for(let i=0;i<200;i++)T.record('info','event '+i);
assert.equal(context.LastSetDiagnostics.logs().length,120);
assert(source.includes('data-ls-diagnostics-copy'));
assert(source.includes('navigator.clipboard'));
assert(!source.includes('localStorage'));
console.log('LastSet diagnostics smoke tests passed');
