const assert=require('assert');
global.__LASTSET_TEST_ONLY__=true;
require('../lastset-offline.js');
const T=global.LastSetOfflineTest;
assert(T,'Offline test API missing');
assert.deepEqual(T.statusCopy(true),{label:'Offline',detail:'Training is saved on this device.'});
assert.equal(T.sameOriginAsset('/lastset-explore.js','https://lastset.example'),true);
assert.equal(T.sameOriginAsset('https://lastset.example/assets/a.svg','https://lastset.example'),true);
assert.equal(T.sameOriginAsset('https://other.example/a.js','https://lastset.example'),false);
assert.equal(T.sameOriginAsset('/api/sync','https://lastset.example'),false);
const fs=require('fs');
const sw=fs.readFileSync('service-worker.js','utf8');
const boot=fs.readFileSync('app-v12.html','utf8');
assert.ok(sw.includes("const CACHE = 'lastset-v1-beta1-01700'"),'Offline cache version missing');
assert.ok(sw.includes("caches.match(request,{ignoreSearch:true})"),'Versioned asset cache matching must ignore search params');
assert.ok(sw.includes("LASTSET_WARM_OFFLINE"),'Offline warm-cache message handler missing');
assert.ok(sw.includes("OFFLINE_SHELL"),'Dedicated WebKit offline shell key missing');
assert.ok(sw.includes("primeOfflineCache"),'Offline shell priming routine missing');
assert.ok(sw.includes("await cache.match(OFFLINE_SHELL)"),'Offline navigation must try the stable shell first');
assert.ok(sw.includes("'./lastset-anatomy.js'"),'Anatomy JS must be precached');
assert.ok(sw.includes("'./lastset-anatomy.css'"),'Anatomy CSS must be precached');
assert.ok(sw.includes("'./lastset-explore.js'"),'Explore JS must be precached');
assert.ok(sw.includes("'./lastset-offline.js'"),'Offline JS must be precached');
assert.ok(!boot.includes('unregister()'),'Bootstrap must not unregister the service worker');
assert.ok(!boot.includes('caches.delete('),'Bootstrap must not delete offline caches');
console.log('LastSet offline smoke tests passed');