const assert=require('assert');
global.__LASTSET_TEST_ONLY__=true;
require('../lastset-onboarding.js');
const T=global.LastSetOnboardingTest;
assert(T,'Onboarding test API missing');
assert(T.meaningfulName('Thiva'));
assert(!T.meaningfulName('Current user'));
assert(!T.meaningfulName('New user'));
assert(T.profileComplete({name:'Thiva',weightUnit:'kg',onboardingComplete:true}));
assert(!T.profileComplete({name:'Thiva',weightUnit:'kg'}));
assert.equal(T.bodyWeightKg(220,'lb'),99.8);
const mem=new Map();
const storage={getItem:k=>mem.has(k)?mem.get(k):null,setItem:(k,v)=>mem.set(k,v)};
storage.setItem('lastset-user-spaces-v1',JSON.stringify({version:1,activeId:'u1',users:[{id:'u1',name:'Thiva',data:{sessions:{},profile:{name:'Thiva',weightUnit:'kg'}}},{id:'u2',name:'Current user',data:{sessions:{},profile:{name:'',weightUnit:'kg'}}}]}));
const current={sessions:{},profile:{name:'Thiva',weightUnit:'kg'}};
assert(T.migrateExisting(current,storage));
assert.equal(current.profile.onboardingComplete,true);
const reg=T.readRegistry(storage);
assert.equal(reg.users[0].data.profile.onboardingComplete,true);
assert.equal(reg.users[1].data.profile.onboardingComplete,undefined);
const rec=T.newUserRecord({name:'New Person',weightUnit:'kg'},'u3',123);
assert.equal(rec.name,'New Person');
assert.equal(rec.data.profile.onboardingComplete,true);
assert.equal(rec.data.profile.userId,'u3');
assert.deepEqual(rec.data.sessions,{});
console.log('LastSet onboarding smoke tests passed');