const assert=require('node:assert/strict');
const fs=require('node:fs');
const sw=fs.readFileSync('service-worker.js','utf8');
const worker=fs.readFileSync('worker.js','utf8');
const build=fs.readFileSync('build-cloudflare.sh','utf8');
const stamp=fs.readFileSync('scripts/stamp-release.mjs','utf8');
const boot=fs.readFileSync('index.html','utf8');
assert(worker.includes('lastset-build.json'),'Worker must obtain release identity');
assert(worker.includes('stampExternalAssets'),'Server HTML must version every JS/CSS tag');
assert(worker.includes('lastset-diagnostics.js'),'Diagnostic script must be injected before app boot');
assert(worker.includes('no-store'),'Navigation must bypass HTTP cache');
assert(sw.includes('__LASTSET_BUILD_ID__'),'Offline cache must be keyed to release');
assert(sw.includes('staticResponse'),'Offline asset handler must be installed');
assert(sw.includes("networkFirstAsset"),'JS/CSS should use network-first caching');
assert(sw.includes("'./lastset-diagnostics.js'"),'Diagnostics JS must be included offline');
assert(sw.includes("'./lastset-diagnostics.css'"),'Diagnostics CSS must be included offline');
assert(boot.includes('lastset-diagnostics.js'),'Diagnostics must load before inline application');
assert(boot.indexOf('lastset-diagnostics.js')<boot.indexOf('const EXERCISES = ['),'Diagnostics loaded too late');
assert(build.includes('scripts/stamp-release.mjs'),'Bundle must tag release identity');
assert(stamp.includes("LASTSET_RELEASE_ID")&&stamp.includes('GITHUB_SHA'),'Build version should follow commit');
assert(fs.existsSync('lastset-diagnostics.js'));
assert(fs.existsSync('lastset-diagnostics.css'));
assert(!sw.includes("if(cached){\n    event.waitUntil("),'Old stale-while-revalidate JS logic still present');
console.log('LastSet versioning smoke tests passed');
